package tech.kuiperbelt.lib.common.datarest;

import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.web.filter.ForwardedHeaderFilter;

/**
 * Customized Spring data rest config
 */
@Configuration
@Import({KuiperbeltDataRestExceptionHandlerAdvice.class,MvcValidatorHandler.class, LogHandler.class})
public class KuiperbeltDataRestAutoConfig {

    /**
     * Customized Spring data rest config
     * @return
     */
    @Bean
    @ConditionalOnMissingBean
    public KuiperbeltRepositoryRestConfigurer kuiperbeltRepositoryRestConfigurer() {
        return new KuiperbeltRepositoryRestConfigurer();
    }

    /**
     * Forwarded Header. It will impact the "HEATOS Link" generated by Spring data rest
     * @return
     */
    @Bean
    public FilterRegistrationBean<ForwardedHeaderFilter> forwardedHeaderFilter() {
        FilterRegistrationBean<ForwardedHeaderFilter> bean = new FilterRegistrationBean<>();
        bean.setFilter(new ForwardedHeaderFilter());
        return bean;
    }

    /**
     * Wrap all spring data rest event handler in one transaction.
     * @param transactionManager
     * @return
     */
    @Bean
    public KuiperbeltDataRestTransactionAspect springDataRestTransactionAspect(PlatformTransactionManager transactionManager) {
        return new KuiperbeltDataRestTransactionAspect(transactionManager);
    }

}
